/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/* 
 * Cryption.java
 *
 * Created on Mar 30, 2012, 3:25:47 PM
 */

package net.filterlogic.OpenCapture.utils;

import net.filterlogic.OpenCapture.crypto.Crypt;
import net.filterlogic.util.StringUtils;

/**
 *
 * @author dnesbitt
 */
public class Cryption extends javax.swing.JFrame {

    /** Creates new form Cryption */
    public Cryption() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtPassphrase = new javax.swing.JTextField();
        jlblPassphrase = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaUnencrypted = new javax.swing.JTextArea();
        jlblUnencrypted = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaEncrypted = new javax.swing.JTextArea();
        jlblEncrypted = new javax.swing.JLabel();
        jbtnEncrypt = new javax.swing.JButton();
        jbtnDecrypt = new javax.swing.JButton();
        jlblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cryption - Pulsestream Internet Services");
        setResizable(false);

        jtxtPassphrase.setEnabled(false);

        jlblPassphrase.setText("Passphrase");

        jtaUnencrypted.setColumns(20);
        jtaUnencrypted.setRows(5);
        jScrollPane1.setViewportView(jtaUnencrypted);

        jlblUnencrypted.setText("Unencrypted Text");

        jtaEncrypted.setColumns(20);
        jtaEncrypted.setRows(5);
        jScrollPane2.setViewportView(jtaEncrypted);

        jlblEncrypted.setText("Encrypted Text");

        jbtnEncrypt.setText("Encrypt");
        jbtnEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEncryptActionPerformed(evt);
            }
        });

        jbtnDecrypt.setText("Decrypt");
        jbtnDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDecryptActionPerformed(evt);
            }
        });

        jlblStatus.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jlblStatus.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlblPassphrase, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtPassphrase, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlblUnencrypted, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlblEncrypted, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnEncrypt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jbtnDecrypt)))
                .addContainerGap())
            .addComponent(jlblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlblPassphrase)
                .addGap(4, 4, 4)
                .addComponent(jtxtPassphrase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblUnencrypted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblEncrypted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEncrypt)
                    .addComponent(jbtnDecrypt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEncryptActionPerformed

//        String passPhrase = jtxtPassphrase.getText();
//
//        if(passPhrase.length()<1)
//        {
//            jlblStatus.setText("Error, no passphrase provided!");
//            return;
//        }
//
//        byte[] myKey = passPhrase.getBytes();

        String data = jtaUnencrypted.getText();

        if(data.length()<1)
        {
            jlblStatus.setText("Error, no data  in Unencrypted field!");
            return;
        }

        Crypt crypt = new Crypt("DES");
        //Crypt crypt = new Crypt(passPhrase.getBytes(), "DES");

        String encryptedString = crypt.encryptHexString(data);

        jtaEncrypted.setText(encryptedString);
        jtaUnencrypted.setText("");
    }//GEN-LAST:event_jbtnEncryptActionPerformed

    private void jbtnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDecryptActionPerformed
//        String passPhrase = jtxtPassphrase.getText();
//
//        if(passPhrase.length()<1)
//        {
//            jlblStatus.setText("Error, no passphrase provided!");
//            return;
//        }
//
//        byte[] myKey = passPhrase.getBytes();

        String data = jtaEncrypted.getText();

        if(data.length()<1)
        {
            jlblStatus.setText("Error, no data  in Unencrypted field!");
            return;
        }

        Crypt crypt = new Crypt("DES");
        //Crypt crypt = new Crypt(passPhrase.getBytes(), "DES");

        String unencryptedString = crypt.decryptHexString(data);

        jtaUnencrypted.setText(unencryptedString);
        jtaEncrypted.setText("");

    }//GEN-LAST:event_jbtnDecryptActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cryption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnDecrypt;
    private javax.swing.JButton jbtnEncrypt;
    private javax.swing.JLabel jlblEncrypted;
    private javax.swing.JLabel jlblPassphrase;
    private javax.swing.JLabel jlblStatus;
    private javax.swing.JLabel jlblUnencrypted;
    private javax.swing.JTextArea jtaEncrypted;
    private javax.swing.JTextArea jtaUnencrypted;
    private javax.swing.JTextField jtxtPassphrase;
    // End of variables declaration//GEN-END:variables

}
